<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- REPORT GENERATOR -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),USE*,Facet*,SN*,UF*,BT*,NT*,RT*,CN*,HN*,FUN*,TTCRef*,TTCSubd*,TTCSubj*,FCNgmgpc*,FCNlctgm*,TNR*,TTCForm*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT USE (#PCDATA)>
<!ELEMENT Facet (#PCDATA)>
<!ELEMENT SN (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT RT (#PCDATA)>
<!ELEMENT CN (#PCDATA)>
<!ELEMENT HN (#PCDATA)>
<!ELEMENT FUN (#PCDATA)>
<!ELEMENT TTCRef (#PCDATA)>
<!ELEMENT TTCSubd (#PCDATA)>
<!ELEMENT TTCSubj (#PCDATA)>
<!ELEMENT FCNgmgpc (#PCDATA)>
<!ELEMENT FCNlctgm (#PCDATA)>
<!ELEMENT TNR (#PCDATA)>
<!ELEMENT TTCForm (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <NON-DESCRIPTOR>3-D photographs</NON-DESCRIPTOR>
 <USE>Three-dimensional photographs</USE>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <TNR>tgm013005</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>3-in-1 pictures</NON-DESCRIPTOR>
 <USE>Three-in-one pictures</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000001</FCNgmgpc>
 <FCNlctgm>lctgm000002</FCNlctgm>
 <TNR>tgm000002</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>A la poupée prints</DESCRIPTOR>
 <SN>Color prints made by simultaneously inking separate areas of the same plate or block with different colors, before printing.</SN>
 <UF>Poupée prints</UF>
 <BT>Prints</BT>
 <RT>Intaglio prints</RT>
 <RT>Relief prints</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000002</FCNgmgpc>
 <FCNlctgm>lctgm000006</FCNlctgm>
 <TNR>tgm000006</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>A trois crayons drawings</DESCRIPTOR>
 <SN>Chalk drawings in three colors, usually red, white, and black.</SN>
 <UF>Three chalk drawings</UF>
 <UF>Trois crayons drawings</UF>
 <BT>Chalk drawings</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000003</FCNgmgpc>
 <FCNlctgm>lctgm000007</FCNlctgm>
 <TNR>tgm000007</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Äac prints</NON-DESCRIPTOR>
 <USE>Photochrom prints</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000004</FCNgmgpc>
 <FCNlctgm>lctgm000008</FCNlctgm>
 <TNR>tgm000008</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Abstract drawings</DESCRIPTOR>
 <BT>Abstract works</BT>
 <BT>Drawings</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000005</FCNgmgpc>
 <FCNlctgm>lctgm000031</FCNlctgm>
 <TNR>tgm000031</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Abstract paintings</DESCRIPTOR>
 <BT>Abstract works</BT>
 <BT>Paintings</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000006</FCNgmgpc>
 <FCNlctgm>lctgm000032</FCNlctgm>
 <TNR>tgm000032</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Abstract photographs</DESCRIPTOR>
 <BT>Abstract works</BT>
 <BT>Photographs</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000007</FCNgmgpc>
 <FCNlctgm>lctgm000033</FCNlctgm>
 <TNR>tgm000033</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Abstract prints</DESCRIPTOR>
 <BT>Abstract works</BT>
 <BT>Prints</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000008</FCNgmgpc>
 <FCNlctgm>lctgm000034</FCNlctgm>
 <TNR>tgm000034</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Abstract works</DESCRIPTOR>
 <SN>Images in which the depiction of real objects has been subordinated or entirely discarded; especially non-representational images, stressing formal relationships of line, color, and shape.</SN>
 <BT>Pictures</BT>
 <NT>Abstract drawings</NT>
 <NT>Abstract paintings</NT>
 <NT>Abstract photographs</NT>
 <NT>Abstract prints</NT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000009</FCNgmgpc>
 <FCNlctgm>lctgm000036</FCNlctgm>
 <TNR>tgm000036</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Acetate negatives</DESCRIPTOR>
 <SN>Acetate safety films were first introduced in the early 1900s.  Various types include diacetate and triacetate and are often difficult to distinguish from one another.</SN>
 <UF>Cellulose acetate negatives</UF>
 <UF>Cellulose diacetate negatives</UF>
 <UF>Cellulose triacetate negatives</UF>
 <UF>Diacetate negatives</UF>
 <UF>Triacetate negatives</UF>
 <BT>Safety film negatives</BT>
 <HN>Changed 6/94. Formerly, ACETATE NEGATIVES may have been indexed as CELLULOSE DIACETATE NEGATIVES or as CELLULOSE TRIACETATE NEGATIVES.</HN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000010</FCNgmgpc>
 <FCNlctgm>lctgm000050</FCNlctgm>
 <TNR>tgm000050</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Acrylic paintings</DESCRIPTOR>
 <BT>Polymer paintings</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000011</FCNgmgpc>
 <FCNlctgm>lctgm000061</FCNlctgm>
 <TNR>tgm000061</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Action comics</NON-DESCRIPTOR>
 <USE>Adventure comics</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000012</FCNgmgpc>
 <FCNlctgm>lctgm000062</FCNlctgm>
 <TNR>tgm000062</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Ads</NON-DESCRIPTOR>
 <USE>Advertisements</USE>
 <USE>Advertising</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000013</FCNgmgpc>
 <FCNlctgm>lctgm000092</FCNlctgm>
 <TNR>tgm000092</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Adventure comics</DESCRIPTOR>
 <SN>Comics featuring heroes and heroines involved in action-packed, danger-filled stories. Examples include Flash Gordon, Superman, and Tarzan.</SN>
 <UF>Action comics</UF>
 <BT>Comics</BT>
 <RT>Comic books</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000014</FCNgmgpc>
 <FCNlctgm>lctgm000098</FCNlctgm>
 <TNR>tgm000097</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Advertisements</DESCRIPTOR>
 <SN>Public notices of the availability of goods or services through purchase or other means.</SN>
 <UF>Ads</UF>
 <BT>Ephemera</BT>
 <NT>Advertising cards</NT>
 <NT>Direct mail</NT>
 <NT>Display cards</NT>
 <NT>Promotional materials</NT>
 <RT>Cameos (Stamps)</RT>
 <RT>Fashion photographs</RT>
 <RT>Fashion prints</RT>
 <RT>Medley prints</RT>
 <RT>Painted wall signs</RT>
 <RT>Premiums</RT>
 <RT>Publicity photographs</RT>
 <CN>Also index under BROADSIDES, HANDBILLS, POSTERS, or other appropriate form.</CN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000015</FCNgmgpc>
 <FCNlctgm>lctgm000099</FCNlctgm>
 <TNR>tgm000098</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Advertising cards</DESCRIPTOR>
 <SN>Cards issued to promote goods or services.  May have been distributed by merchants or enclosed as premiums with such products as bread, cigarettes, and coffee.  Usually, cards bear seller or product name and a pictorial representation of the service or product.  Picture may also be unrelated to the product.</SN>
 <UF>Insert cards</UF>
 <UF>Tradecards</UF>
 <UF>Trading cards</UF>
 <BT>Advertisements</BT>
 <BT>Cards</BT>
 <NT>Sailing cards</NT>
 <NT>Stock cards</NT>
 <NT>Trade cards</NT>
 <RT>Business cards</RT>
 <RT>Collecting cards</RT>
 <RT>Sports cards</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000016</FCNgmgpc>
 <FCNlctgm>lctgm000102</FCNlctgm>
 <TNR>tgm000101</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Advertising mail</NON-DESCRIPTOR>
 <USE>Direct mail</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000017</FCNgmgpc>
 <FCNlctgm>lctgm000103</FCNlctgm>
 <TNR>tgm000102</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Aerial photographs</DESCRIPTOR>
 <SN>Photographs taken from an air-borne vehicle within the earth&apos;s atmosphere, such as an airplane, balloon, or kite; from a camera strapped to a bird; or by a person, such as a parachutist, in flight.  Use SPACE PHOTOGRAPHS for images taken from beyond the earth&apos;s atmosphere.</SN>
 <BT>Aerial views</BT>
 <BT>Photographs</BT>
 <RT>Space photographs</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000018</FCNgmgpc>
 <FCNlctgm>lctgm000108</FCNlctgm>
 <TNR>tgm000107</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Aerial views</DESCRIPTOR>
 <SN>Views from a high vantage point.</SN>
 <UF>Air views</UF>
 <UF>Balloon views</UF>
 <UF>Views, Aerial</UF>
 <BT>Views</BT>
 <NT>Aerial photographs</NT>
 <RT>Bird&apos;s-eye views</RT>
 <RT>Panoramic views</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000019</FCNgmgpc>
 <FCNlctgm>lctgm000112</FCNlctgm>
 <TNR>tgm000111</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Agfacolor transparencies</NON-DESCRIPTOR>
 <USE>Dye coupler transparencies</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000020</FCNgmgpc>
 <FCNlctgm>lctgm000134</FCNlctgm>
 <TNR>tgm000133</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Air conditioning, heating, &amp; ventilating drawings</NON-DESCRIPTOR>
 <USE>HVAC drawings</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000021</FCNgmgpc>
 <FCNlctgm>lctgm000164</FCNlctgm>
 <TNR>tgm000163</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Air views</NON-DESCRIPTOR>
 <USE>Aerial views</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000022</FCNgmgpc>
 <FCNlctgm>lctgm000185</FCNlctgm>
 <TNR>tgm000184</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Airbrush works</DESCRIPTOR>
 <BT>Pictures</BT>
 <RT>Paintings</RT>
 <RT>Photographs</RT>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000023</FCNgmgpc>
 <FCNlctgm>lctgm000187</FCNlctgm>
 <TNR>tgm000186</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Albertypes</NON-DESCRIPTOR>
 <USE>Collotypes</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000024</FCNgmgpc>
 <FCNlctgm>lctgm000223</FCNlctgm>
 <TNR>tgm000222</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Album cards</DESCRIPTOR>
 <SN>Collecting cards intended for display in albums; popular from about 1850 to 1890.  They usually lack a publisher&apos;s name or date and do not have advertising on them.</SN>
 <BT>Collecting cards</BT>
 <HN>Changed 10/90.  Formerly, ALBUM CARDS may have been indexed as COLLECTING CARDS.</HN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000025</FCNgmgpc>
 <FCNlctgm>lctgm000225</FCNlctgm>
 <TNR>tgm000224</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Album covers</DESCRIPTOR>
 <SN>Containers for sound recordings; printed with graphic designs.</SN>
 <UF>Covers, Album</UF>
 <UF>Covers, Record</UF>
 <UF>Jackets, Record</UF>
 <UF>Record covers</UF>
 <UF>Record jackets</UF>
 <UF>Sleeves, Record</UF>
 <BT>Covers (Illustration)</BT>
 <HN>Changed 6/94. Formerly, ALBUM COVERS may have been indexed as RECORD JACKETS.</HN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000026</FCNgmgpc>
 <FCNlctgm>lctgm000226</FCNlctgm>
 <TNR>tgm000225</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Albumen prints</DESCRIPTOR>
 <SN>Predominant paper print photographic process in the 1800s; popular 1850s-1890s.</SN>
 <UF>Albumen photoprints</UF>
 <BT>Silver printing-out paper prints</BT>
 <NT>Crystalographs</NT>
 <RT>Crystoleums</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000027</FCNgmgpc>
 <FCNlctgm>lctgm000228</FCNlctgm>
 <TNR>tgm000227</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Albumen transparencies</DESCRIPTOR>
 <SN>Typically, glass lantern slides or stereographs; introduced 1849; largely replaced by collodion transparencies.</SN>
 <UF>Hyalotypes</UF>
 <BT>Glass transparencies</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000028</FCNgmgpc>
 <FCNlctgm>lctgm000229</FCNlctgm>
 <TNR>tgm000228</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Albums (Books)</DESCRIPTOR>
 <SN>Bound or loose-leaf sets of pages. Includes handmade albums and published volumes of blank pages designed for the addition of images or keepsakes.</SN>
 <UF>Souvenir albums</UF>
 <BT>Books</BT>
 <NT>Photograph albums</NT>
 <NT>Presentation albums</NT>
 <NT>Scrapbooks</NT>
 <NT>Sketchbooks</NT>
 <RT>Sample books</RT>
 <HN>Changed 6/94. Formerly, some albums may have been indexed as SOUVENIR ALBUMS.</HN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000029</FCNgmgpc>
 <FCNlctgm>lctgm000230</FCNlctgm>
 <TNR>tgm000229</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Allegorical drawings</DESCRIPTOR>
 <BT>Allegories</BT>
 <BT>Drawings</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000030</FCNgmgpc>
 <FCNlctgm>lctgm000247</FCNlctgm>
 <TNR>tgm000246</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Allegorical paintings</DESCRIPTOR>
 <BT>Allegories</BT>
 <BT>Paintings</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000031</FCNgmgpc>
 <FCNlctgm>lctgm000248</FCNlctgm>
 <TNR>tgm000247</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Allegorical photographs</DESCRIPTOR>
 <BT>Allegories</BT>
 <BT>Photographs</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000032</FCNgmgpc>
 <FCNlctgm>lctgm000249</FCNlctgm>
 <TNR>tgm000248</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Allegorical prints</DESCRIPTOR>
 <BT>Allegories</BT>
 <BT>Prints</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000033</FCNgmgpc>
 <FCNlctgm>lctgm000250</FCNlctgm>
 <TNR>tgm000249</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Allegories</DESCRIPTOR>
 <SN>Representations of truths or generalizations about human existence by means of symbolic images; often of classical derivation.</SN>
 <UF>Allegorical works</UF>
 <BT>Pictures</BT>
 <NT>Allegorical drawings</NT>
 <NT>Allegorical paintings</NT>
 <NT>Allegorical photographs</NT>
 <NT>Allegorical prints</NT>
 <RT>Allusions</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000034</FCNgmgpc>
 <FCNlctgm>lctgm000251</FCNlctgm>
 <TNR>tgm000250</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Allusions</DESCRIPTOR>
 <SN>Representations of or references to one work in another work. Does not include routine reproductions or works made &quot;after&quot; other works.</SN>
 <BT>Concepts</BT>
 <RT>Allegories</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000035</FCNgmgpc>
 <FCNlctgm>lctgm000262</FCNlctgm>
 <TNR>tgm000261</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Amateur works</DESCRIPTOR>
 <SN>Images created by people who are not full-time or professional practitioners in the medium or genre; often made for pleasure rather than money; does not refer to image quality.</SN>
 <BT>Pictures</BT>
 <RT>Children&apos;s art</RT>
 <RT>Juvenilia</RT>
 <RT>Snapshots</RT>
 <RT>Student works</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000036</FCNgmgpc>
 <FCNlctgm>lctgm000283</FCNlctgm>
 <TNR>tgm000282</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Ambrotypes</DESCRIPTOR>
 <SN>Direct-image photographs; the chemically reduced collodion glass negative packaged against a dark background appears as a positive. Commonly in a case; popular mid-1850s to mid-1860s.</SN>
 <UF>Cased photographs</UF>
 <UF>Collodion positive photographs</UF>
 <BT>Photographs</BT>
 <CN>Used in a note under PHOTOGRAPHS.</CN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000037</FCNgmgpc>
 <FCNlctgm>lctgm000285</FCNlctgm>
 <TNR>tgm000284</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Anaglyphs</DESCRIPTOR>
 <SN>Photomechanical images in two contrasting colors, such as red and green.  Printed either as a pair of images or as one image superimposed on the other but slightly out of registry.  When viewed through a pair of lenses, each in the appropriate different color, a three-dimensional effect is created.  Introduced in 1891; popular during the 1920s.</SN>
 <BT>Novelty works</BT>
 <BT>Photomechanical prints</BT>
 <BT>Stereographs</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000038</FCNgmgpc>
 <FCNlctgm>lctgm000307</FCNlctgm>
 <TNR>tgm000306</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Anamorphic images</DESCRIPTOR>
 <SN>Images produced by a distorting optical system or other method that renders an image unrecognizable unless viewed by the proper restoring device. Popular for prints and drawings in the 1600s and 1700s and for photographs in the 1800s.  Images are often recorded as they appear in a convex or concave cylindrical mirror.</SN>
 <BT>Novelty works</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000039</FCNgmgpc>
 <FCNlctgm>lctgm000309</FCNlctgm>
 <TNR>tgm000308</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Animation cels</DESCRIPTOR>
 <SN>Images on celluloid or polyester sheets, which are used to create an animated sequence for movie, videotape, or other moving image productions; usually drawings or paintings.</SN>
 <UF>Cartoon cels</UF>
 <UF>Cels, Animation</UF>
 <BT>Pictures</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000040</FCNgmgpc>
 <FCNlctgm>lctgm000359</FCNlctgm>
 <TNR>tgm000358</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Announcements</DESCRIPTOR>
 <SN>Small notices of special occasions, such as weddings.</SN>
 <BT>Ephemera</BT>
 <RT>Broadsides</RT>
 <RT>Invitations</RT>
 <FUN>Formerly TGMI and TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000041</FCNgmgpc>
 <FCNlctgm>lctgm000362</FCNlctgm>
 <TNR>tgm000361</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Anthropological photographs</NON-DESCRIPTOR>
 <USE>Ethnographic photographs</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000042</FCNgmgpc>
 <FCNlctgm>lctgm000373</FCNlctgm>
 <TNR>tgm000372</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Aquatints</DESCRIPTOR>
 <BT>Intaglio prints</BT>
 <NT>Sugar-lift aquatints</NT>
 <RT>Etchings</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000043</FCNgmgpc>
 <FCNlctgm>lctgm000433</FCNlctgm>
 <TNR>tgm000432</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Architectural drawings</DESCRIPTOR>
 <SN>Graphic delineations made for the design and construction (or documentation of design and construction) of sites, structures, details, fixtures, furnishings, and decorations, as well as other objects designed by an architect or architectural office.</SN>
 <UF>Drawings, Architectural</UF>
 <BT>Design drawings</BT>
 <CN>Also index under terms that express the type of projection or purpose, listed under PROJECTIONS and DESIGN DRAWINGS.  Used in a note under ENGINEERING DRAWINGS, LANDSCAPE ARCHITECTURE DRAWINGS, and NAVAL ARCHITECTURE DRAWINGS.</CN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000044</FCNgmgpc>
 <FCNlctgm>lctgm000456</FCNlctgm>
 <TNR>tgm000455</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Architectural photographs</DESCRIPTOR>
 <SN>Photographs made to record a structure for architects, architectural historians, and others who need clear representations of such aspects as construction phases, exteriors, or interiors. Not meant for every photo of a structure.</SN>
 <BT>Photographs</BT>
 <NT>Progress photographs</NT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000045</FCNgmgpc>
 <FCNlctgm>lctgm000465</FCNlctgm>
 <TNR>tgm000464</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Aristotypes</DESCRIPTOR>
 <SN>Photographic prints made on various non-albumen papers. The trade name became a general term for prints made on collodion silver chloride printing-out papers (introduced in the 1860s) and was later applied to gelatin silver chloride papers (introduced in the 1880s).</SN>
 <BT>Collodion printing-out paper prints</BT>
 <BT>Gelatin silver printing-out paper prints</BT>
 <HN>Changed 6/94. Formerly, ARISTOTYPES may have been indexed as COLLODION PRINTING-OUT PAPER PRINTS.</HN>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000046</FCNgmgpc>
 <FCNlctgm>lctgm000476</FCNlctgm>
 <TNR>tgm000475</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Armorial bearings</NON-DESCRIPTOR>
 <USE>Coats of arms</USE>
 <FUN>Formerly TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000047</FCNgmgpc>
 <TNR>tgm000488</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Armorial bookplates</DESCRIPTOR>
 <SN>Book plates bearing such heraldic devices as coats of arms.</SN>
 <UF>Heraldic bookplates</UF>
 <BT>Bookplates</BT>
 <RT>Coats of arms</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000048</FCNgmgpc>
 <FCNlctgm>lctgm000489</FCNlctgm>
 <TNR>tgm000489</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Art by children</NON-DESCRIPTOR>
 <USE>Children&apos;s art</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000049</FCNgmgpc>
 <FCNlctgm>lctgm000513</FCNlctgm>
 <TNR>tgm000513</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Art exhibition posters</NON-DESCRIPTOR>
 <USE>Exhibition posters</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000050</FCNgmgpc>
 <FCNlctgm>lctgm000521</FCNlctgm>
 <TNR>tgm000521</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Art reproductions</DESCRIPTOR>
 <SN>Commercially published, mechanically printed copies of individual paintings, prints, drawings, and other two-dimensional works of art.</SN>
 <BT>Reproductions</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000051</FCNgmgpc>
 <FCNlctgm>lctgm000527</FCNlctgm>
 <TNR>tgm000527</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Artists&apos; devices</DESCRIPTOR>
 <SN>Designs, symbols, or mottoes used by artists to identify their creations.</SN>
 <UF>Devices, Artists&apos;</UF>
 <UF>Symbols, Artists&apos;</UF>
 <BT>Emblems</BT>
 <RT>Artists&apos; signatures</RT>
 <RT>Monograms</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000052</FCNgmgpc>
 <FCNlctgm>lctgm000549</FCNlctgm>
 <TNR>tgm000548</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Artists&apos; early works</NON-DESCRIPTOR>
 <USE>Juvenilia</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000053</FCNgmgpc>
 <FCNlctgm>lctgm000550</FCNlctgm>
 <TNR>tgm000549</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Artists&apos; proofs</DESCRIPTOR>
 <SN>Prints which are accepted for an edition but are unnumbered or numbered separately from the edition and reserved for the artist&apos;s use.</SN>
 <BT>Proofs</BT>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000054</FCNgmgpc>
 <FCNlctgm>lctgm000553</FCNlctgm>
 <TNR>tgm000552</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Artists&apos; signatures</DESCRIPTOR>
 <BT>Autographs</BT>
 <RT>Artists&apos; devices</RT>
 <RT>Chops</RT>
 <FUN>Formerly TGMI term &amp; TGMII term. SN: Signatures of artists, photographers, painters, or printmakers</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000055</FCNgmgpc>
 <FCNlctgm>lctgm000554</FCNlctgm>
 <TNR>tgm000553</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <NON-DESCRIPTOR>Artotypes</NON-DESCRIPTOR>
 <USE>Collotypes</USE>
 <FUN>Formerly TGMI term (nonpostable) &amp; TGMII term (nonpostable).</FUN>
 <TTCSubj>Subject (MARC 450)</TTCSubj>
 <FCNgmgpc>gmgpc000056</FCNgmgpc>
 <FCNlctgm>lctgm000556</FCNlctgm>
 <TNR>tgm000555</TNR>
 <TTCForm>Genre/Format (MARC 455)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>As-built drawings</DESCRIPTOR>
 <SN>Final set of working drawings incorporating (through revisions or annotations) any changes  of dimensions, materials, form, and method of construction encountered in the completion of the structure or site.</SN>
 <UF>Drawings, As-built</UF>
 <BT>Working drawings</BT>
 <RT>Record drawings</RT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000057</FCNgmgpc>
 <FCNlctgm>lctgm000591</FCNlctgm>
 <TNR>tgm000590</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Auction catalogs</DESCRIPTOR>
 <BT>Catalogs</BT>
 <FUN>Formerly TGMI term &amp; TGMII term.</FUN>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <FCNgmgpc>gmgpc000058</FCNgmgpc>
 <FCNlctgm>lctgm000617</FCNlctgm>
 <TNR>tgm000616</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Audiocassettes</DESCRIPTOR>
 <UF>Audio cassettes</UF>
 <UF>Cassettes, Audio</UF>
 <BT>Audiotapes</BT>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <TNR>tgm012458</TNR>
 <TTCForm>Genre/Format (MARC 155/655)</TTCForm>
</CONCEPT>
<CONCEPT>
 <DESCRIPTOR>Audiotapes</DESCRIPTOR>
 <UF>Audio tapes</UF>
 <BT>Magnetic tapes</BT>
 <BT>Sound recordings</BT>
 <NT>Audiocassettes</NT>
 <RT>Sound equipment &amp; supplies</RT>
 <TTCSubj>Subject (MARC 150/650)</TTCSubj>
 <TNR>tgm012465</TNR>